language: node_js
node_js:
- '6'
before_install:
- npm install -g npm@^4
cache: yarn
before_deploy:
- yarn manualPrepublish
deploy:
  provider: npm
  email: kegan+isogon@keganmyers.com
  api_key:
    secure: OtRyB1Eovxs4ahZlVR0jEzmfutSHA0ldhpwE/1F1Ed2ZmBBzouqdSSxnY9urcb1QlM7D/RUXvMnDosUfHVesXkGpp+j3Oar/QmrBGhf2pKiwIvGqY23YKI1NKW8llYuWVgLyCKYF+vCw5lT2OoqRTEUqEV45T3BU3myU/greOzF7Q8M1Wl9DYXlGoIinYJl9Y9gW3YKFvAACaWye8QeCeSzVWDgPkx3EfUvZbhxq/sB3plm5yvNxLckIw9j1+PHjjjl9CVmihjFpleBX+Z9zUUltqBewrV8qappdA7DoXVbkwa69Y+npv+d52JqW2uZgRzi1RxKQK7r+wL7EAZxYq2XCFQUyvb8gAIpJW/1d9Y+W4N+WjuJNCz8dwsFNXOBvcElC+RNor6keBsdsYwIQvRanvBuoHf/oE6LjWerQ/jO+CLHZJ+WXdvSwAE9zxGUbpVz9ZfuAh5YVZkfHptVZgDoF4Ze8Gmjr/nLf7ISbuDL6X9oFAIqrtdaovoeyQddA+AR3tjjLdyJ7OQN8R3AIxVKmjA8xeYSQlW/7hBM3CZS/Wk1ruoXOGsUIb1CPqQdxEr028bn8JIFuqoh6U0rdb5coZaxixFZJT+1fjuz9np9xfUNbsq65i5xFUOu2dsyKgGTgAif1TaNeX2XF3SZPjN7dXRTQDv94Q3IJO73QTmo=
  on:
    tags: true
    repo: isogon/styled-mdl
